name: Update NAV data daily

on:
  schedule:
    - cron: "0 0 * * *" # 00:00 UTC daily
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data fetcher
        run: |
          python fetch_nav.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add nav_eur.csv nav_usd.csv metadata_eur.csv metadata_usd.csv nav_eur.html nav_usd.html || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(data): daily NAV update"
            git push
          else
            echo "No changes to commit"
          fi
